### ISSUE TITLE
Weird behavior on the title

### ISSUE THREAD

**Issue by mahmoud-eslami** [Bilonik/flashy_tab_bar2#2]
There is an issue on title of items in bottom navigation.
The default size of icons is a little bit small and I need to increase it.
There are two scenarios to increase size :

1. passing value to the `iconSize` attribute to increase icon size
2. passing value to the `size` attribute in the Icon widget

I faced issue in both of them 
Set `iconSize` equal 30 :
![SCR-20221019-nxm](https://user-images.githubusercontent.com/57481226/196708611-2824bd60-16f6-44a8-ac24-99acc3927a00.png)
Set size of icon widget equal 30 :
![SCR-20221019-nkq](https://user-images.githubusercontent.com/57481226/196708795-40c88191-6734-4232-9846-ce55d7602d97.png)![SCR-20221019-nzb](https://user-images.githubusercontent.com/57481226/196709089-3b3a496a-2a5c-4998-8d86-98389a25a039.png)

**Comment by Bilonik** [comment]
HI @mahmoud-eslami ,

More than welcome to open a pull request.

Thanks

**Comment by mahmoud-eslami** [comment]
Hi @Bilonik 
Thanks for the response.
I am interested in to work on it, I will give you any update.
