### ISSUE TITLE
Throwing an error on implementation

### ISSUE THREAD

**Issue by imyogisingh** [Bilonik/flashy_tab_bar2#7]
null check operator used on a null value

**Comment by marchacio** [comment]
Same here

**Comment by marchacio** [comment]
> null check operator used on a null value

@imyogisingh  I solved downgrading package version to 0.0.6:
in my _pubspec.yaml_:
```
...
flashy_tab_bar2: 0.0.6
...
```

Note: **DO NOT WRITE** `flashy_tab_bar2: ^0.0.6` (with the '^' character) because it will load the latest version avaible on pub.dev (so the bugged 0.0.9)

**Comment by Bilonik** [comment]
Hi @marchacio and @imyogisingh ,

Version 0.0.10 fix this issue, I upgraded the flutter sdk minimum version and it deprecated Theme.of(context).bottomAppBarTheme.color default value.

Thanks for opening this issue.
